[package]
name = "ataraxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = {git = "https://github.com/serenity-rs/serenity", features = ["unstable_discord_api"]}
unsafe-any = "0.4.2"
